version: 2

updates:

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    registries:
      - github
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - sergeyklay

registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.APP_GITHUB_TOKEN }} # dependabot secret
