name: CI

on:
  push:
    branches:
      # This is to make sure that there is no broken CI on
      # the main branch, and also for Sonarqube integration
      - 'main'
  # We need it for better Sonarqube integration
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analize-with-sonarqube:
    name: Analyze with Sonarqube
    runs-on: ${{ vars.DEFAULT_RUNNER }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Sonar Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
